spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduation_project?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zsj1998520.
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true 
server:
  port: 8899
   