spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gre?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: zsj1998520.
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true 
        ddl-auto: none
server:
  port: 8899
   